# Basic flow where we do all generic tests:
#   - `cargo workspaces exec cargo publish --token ***`: For every crate in our workspace, publish it on crates.io

# Publication flow should run on merge on the `main` branch
on:
  push:
    branches:
      - main

name: Publish

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: rustup component add rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-workspaces
      - uses: actions-rs/cargo@v1
        with:
          command: workspaces
          args: exec cargo publish --token ${{secrets.CARGO_LOGIN}}

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
          override: true
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
          name: Clippy Output