# Basic flow where we do all generic tests:
#   - `cargo workspaces exec cargo publish --dry-run`: Execute a dry run for publication on each crate in the repo, making sure
#   that publication will be possible on merge

# Publication flow should run on PR on the `main` branch
on:
  pull_request:
    branches:
      - main

name: Publish dry run

jobs:
  publish-dry-run:
    name: Publish dry run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions/cache@v2
        id: cache-deps
        with:
          path: |
            ~/.cargo/bin/
          key: ${{ runner.os }}-cargo-workspaces
      - uses: actions-rs/cargo@v1
        if: steps.cache-deps.outputs.cache-hit != 'true'
        with:
          command: install
          args: cargo-workspaces
      - uses: actions-rs/cargo@v1
        with:
          command: workspaces
          args: exec cargo publish --dry-run

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
          override: true
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
          name: Clippy Output